In [1]:
import os
import random
import pandas as pd
import numpy as np

In [2]:
beneficiaries = pd.read_csv("cleaned_data/beneficiary.csv")
carrier = pd.read_csv("cleaned_data/carrier_patient_year.csv")
inpatient = pd.read_csv("cleaned_data/ip_patient_year.csv")
outpatient = pd.read_csv("cleaned_data/op_patient_year.csv")
pde = pd.read_csv("cleaned_data/pde_patient_year.csv")

In [3]:
beneficiaries.columns

Index(['DESYNPUF_ID', 'BENE_BIRTH_DT', 'BENE_SEX_IDENT_CD', 'BENE_RACE_CD',
       'BENE_ESRD_IND', 'SP_STATE_CODE', 'BENE_COUNTY_CD',
       'BENE_HI_CVRAGE_TOT_MONS', 'BENE_SMI_CVRAGE_TOT_MONS',
       'BENE_HMO_CVRAGE_TOT_MONS', 'PLAN_CVRG_MOS_NUM', 'SP_ALZHDMTA',
       'SP_CHF', 'SP_CHRNKIDN', 'SP_CNCR', 'SP_COPD', 'SP_DEPRESSN',
       'SP_DIABETES', 'SP_ISCHMCHT', 'SP_OSTEOPRS', 'SP_RA_OA', 'SP_STRKETIA',
       'MEDREIMB_IP', 'BENRES_IP', 'PPPYMT_IP', 'MEDREIMB_OP', 'BENRES_OP',
       'PPPYMT_OP', 'MEDREIMB_CAR', 'BENRES_CAR', 'PPPYMT_CAR', 'year', 'SEX',
       'RACE', 'STATE'],
      dtype='object')

In [4]:
carrier.columns

Index(['DESYNPUF_ID', 'claim_year', 'num_claim_lines', 'avg_claim_duration',
       'max_claim_duration', 'total_claim_duration',
       'avg_carrier_rejected_amt', 'max_carrier_rejected_amt',
       'total_carrier_rejected_amt', 'avg_carrier_claim_rejected_rate (%)',
       'max_carrier_claim_rejected_rate (%)', 'avg_reimb_allowed_diff',
       'min_reimb_allowed_diff', 'max_reimb_allowed_diff',
       'total_reimb_allowed_diff', 'max_chronic_code_counts',
       'has_Additional endocrine/metabolic burden', 'has_COPD',
       'has_Administrative_screening_aftercare', 'has_Cancer',
       'has_Injury/Frailty Burden', 'has_Additional cardiovascular burden',
       'has_Additional mental health burden',
       'has_Additional Musculoskeletal Burden',
       'has_Infectious disease burden', 'has_Stroke/TIA',
       'has_Additional neurologic burden', 'has_Diabetes',
       'has_Additional renal burden', 'has_Genitourinary (non-renal) burden',
       'has_Sensory Burden', 'has_Additional Hematologic burden',
       'has_Rheumatoid Arthritis/Osteoarthritis', 'has_Depression',
       'has_Heart Failure', 'has_CKD', 'has_Additional GI/Hepatic burden'],
      dtype='object')

In [14]:
v1 = beneficiaries.merge(carrier, left_on=["DESYNPUF_ID", "year"], right_on=["DESYNPUF_ID", "claim_year"], how="left")
v1.head()

,DESYNPUF_ID,BENE_BIRTH_DT,BENE_SEX_IDENT_CD,BENE_RACE_CD,BENE_ESRD_IND,SP_STATE_CODE,BENE_COUNTY_CD,BENE_HI_CVRAGE_TOT_MONS,BENE_SMI_CVRAGE_TOT_MONS,BENE_HMO_CVRAGE_TOT_MONS,PLAN_CVRG_MOS_NUM,SP_ALZHDMTA,SP_CHF,SP_CHRNKIDN,SP_CNCR,SP_COPD,SP_DEPRESSN,SP_DIABETES,SP_ISCHMCHT,SP_OSTEOPRS,SP_RA_OA,SP_STRKETIA,MEDREIMB_IP,BENRES_IP,PPPYMT_IP,MEDREIMB_OP,BENRES_OP,PPPYMT_OP,MEDREIMB_CAR,BENRES_CAR,PPPYMT_CAR,year,SEX,RACE,STATE,claim_year,num_claim_lines,avg_claim_duration,max_claim_duration,total_claim_duration,avg_carrier_rejected_amt,max_carrier_rejected_amt,total_carrier_rejected_amt,avg_carrier_claim_rejected_rate (%),max_carrier_claim_rejected_rate (%),avg_reimb_allowed_diff,min_reimb_allowed_diff,max_reimb_allowed_diff,total_reimb_allowed_diff,max_chronic_code_counts,has_Additional endocrine/metabolic burden,has_COPD,has_Administrative_screening_aftercare,has_Cancer,has_Injury/Frailty Burden,has_Additional cardiovascular burden,has_Additional mental health burden,has_Additional Musculoskeletal Burden,has_Infectious disease burden,has_Stroke/TIA,has_Additional neurologic burden,has_Diabetes,has_Additional renal burden,has_Genitourinary (non-renal) burden,has_Sensory Burden,has_Additional Hematologic burden,has_Rheumatoid Arthritis/Osteoarthritis,has_Depression,has_Heart Failure,has_CKD,has_Additional GI/Hepatic burden
0,000102649ED5601B,1931-10-01,2,1,0,49,290,12,12,0,12,1,0,0,0,1,0,0,0,1,0,1,0.0,0.0,0.0,360.0,90.0,0.0,860.0,170.0,0.0,2008,Female,White,VA,2008.0,16.0,0 days 01:30:00,1 days,1 days,0.000000,0.0,0.0,0.000000,0.0,22.500000,0.0,210.0,360.0,3.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0002278C944E240A,1936-09-01,2,1,1,34,250,12,12,0,12,1,1,1,0,2,1,1,1,1,0,0,0.0,0.0,0.0,2590.0,1530.0,0.0,5000.0,1230.0,0.0,2008,Female,White,NC,2008.0,42.0,0 days 17:08:34.285714285,9 days,30 days,2.142857,50.0,90.0,4.878049,100.0,25.000000,0.0,470.0,1050.0,4.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
2,000330E625C93700,1933-09-01,2,1,0,4,420,12,12,0,0,0,0,0,0,2,0,0,1,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,270.0,150.0,0.0,2008,Female,White,AR,2008.0,4.0,0 days 00:00:00,0 days,0 days,0.000000,0.0,0.0,0.000000,0.0,30.000000,0.0,60.0,120.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,000374D5E110EDA6,1936-08-01,2,1,0,5,90,12,12,0,12,0,0,0,0,2,0,0,1,0,0,0,0.0,0.0,0.0,60.0,30.0,0.0,1090.0,360.0,0.0,2008,Female,White,CA,2008.0,12.0,0 days 00:00:00,0 days,0 days,0.000000,0.0,0.0,0.000000,0.0,20.000000,0.0,130.0,240.0,3.0,1.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0
4,0003950E4B4FEC8D,1940-11-01,2,2,0,19,420,12,12,0,12,0,1,0,0,2,1,0,0,0,0,0,0.0,0.0,0.0,3690.0,420.0,0.0,3590.0,960.0,0.0,2008,Female,Black,LA,2008.0,51.0,0 days 09:24:42.352941176,9 days,20 days,1.568628,80.0,80.0,2.083333,100.0,10.588235,0.0,190.0,540.0,4.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0

In [ ]:
v2 = v1.merge(inpatient

In [15]:
beneficiaries.shape[0]

332694

In [16]:
carrier.shape[0]

262505

In [17]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
v1.head()

,DESYNPUF_ID,BENE_BIRTH_DT,BENE_SEX_IDENT_CD,BENE_RACE_CD,BENE_ESRD_IND,SP_STATE_CODE,BENE_COUNTY_CD,BENE_HI_CVRAGE_TOT_MONS,BENE_SMI_CVRAGE_TOT_MONS,BENE_HMO_CVRAGE_TOT_MONS,PLAN_CVRG_MOS_NUM,SP_ALZHDMTA,SP_CHF,SP_CHRNKIDN,SP_CNCR,SP_COPD,SP_DEPRESSN,SP_DIABETES,SP_ISCHMCHT,SP_OSTEOPRS,SP_RA_OA,SP_STRKETIA,MEDREIMB_IP,BENRES_IP,PPPYMT_IP,MEDREIMB_OP,BENRES_OP,PPPYMT_OP,MEDREIMB_CAR,BENRES_CAR,PPPYMT_CAR,year,SEX,RACE,STATE,claim_year,num_claim_lines,avg_claim_duration,max_claim_duration,total_claim_duration,avg_carrier_rejected_amt,max_carrier_rejected_amt,total_carrier_rejected_amt,avg_carrier_claim_rejected_rate (%),max_carrier_claim_rejected_rate (%),avg_reimb_allowed_diff,min_reimb_allowed_diff,max_reimb_allowed_diff,total_reimb_allowed_diff,max_chronic_code_counts,has_Additional endocrine/metabolic burden,has_COPD,has_Administrative_screening_aftercare,has_Cancer,has_Injury/Frailty Burden,has_Additional cardiovascular burden,has_Additional mental health burden,has_Additional Musculoskeletal Burden,has_Infectious disease burden,has_Stroke/TIA,has_Additional neurologic burden,has_Diabetes,has_Additional renal burden,has_Genitourinary (non-renal) burden,has_Sensory Burden,has_Additional Hematologic burden,has_Rheumatoid Arthritis/Osteoarthritis,has_Depression,has_Heart Failure,has_CKD,has_Additional GI/Hepatic burden
0,000102649ED5601B,1931-10-01,2,1,0,49,290,12,12,0,12,1,0,0,0,1,0,0,0,1,0,1,0.0,0.0,0.0,360.0,90.0,0.0,860.0,170.0,0.0,2008,Female,White,VA,2008.0,16.0,0 days 01:30:00,1 days,1 days,0.000000,0.0,0.0,0.000000,0.0,22.500000,0.0,210.0,360.0,3.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0002278C944E240A,1936-09-01,2,1,1,34,250,12,12,0,12,1,1,1,0,2,1,1,1,1,0,0,0.0,0.0,0.0,2590.0,1530.0,0.0,5000.0,1230.0,0.0,2008,Female,White,NC,2008.0,42.0,0 days 17:08:34.285714285,9 days,30 days,2.142857,50.0,90.0,4.878049,100.0,25.000000,0.0,470.0,1050.0,4.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
2,000330E625C93700,1933-09-01,2,1,0,4,420,12,12,0,0,0,0,0,0,2,0,0,1,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,270.0,150.0,0.0,2008,Female,White,AR,2008.0,4.0,0 days 00:00:00,0 days,0 days,0.000000,0.0,0.0,0.000000,0.0,30.000000,0.0,60.0,120.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,000374D5E110EDA6,1936-08-01,2,1,0,5,90,12,12,0,12,0,0,0,0,2,0,0,1,0,0,0,0.0,0.0,0.0,60.0,30.0,0.0,1090.0,360.0,0.0,2008,Female,White,CA,2008.0,12.0,0 days 00:00:00,0 days,0 days,0.000000,0.0,0.0,0.000000,0.0,20.000000,0.0,130.0,240.0,3.0,1.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0
4,0003950E4B4FEC8D,1940-11-01,2,2,0,19,420,12,12,0,12,0,1,0,0,2,1,0,0,0,0,0,0.0,0.0,0.0,3690.0,420.0,0.0,3590.0,960.0,0.0,2008,Female,Black,LA,2008.0,51.0,0 days 09:24:42.352941176,9 days,20 days,1.568628,80.0,80.0,2.083333,100.0,10.588235,0.0,190.0,540.0,4.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0

In [18]:
v1.shape[0]

332694

In [ ]:
v1

In [8]:
v1.columns[v1.columns.duplicated()]

Index([], dtype='object')

In [9]:
v1.columns

Index(['DESYNPUF_ID', 'BENE_BIRTH_DT', 'BENE_SEX_IDENT_CD', 'BENE_RACE_CD',
       'BENE_ESRD_IND', 'SP_STATE_CODE', 'BENE_COUNTY_CD',
       'BENE_HI_CVRAGE_TOT_MONS', 'BENE_SMI_CVRAGE_TOT_MONS',
       'BENE_HMO_CVRAGE_TOT_MONS', 'PLAN_CVRG_MOS_NUM', 'SP_ALZHDMTA',
       'SP_CHF', 'SP_CHRNKIDN', 'SP_CNCR', 'SP_COPD', 'SP_DEPRESSN',
       'SP_DIABETES', 'SP_ISCHMCHT', 'SP_OSTEOPRS', 'SP_RA_OA', 'SP_STRKETIA',
       'MEDREIMB_IP', 'BENRES_IP', 'PPPYMT_IP', 'MEDREIMB_OP', 'BENRES_OP',
       'PPPYMT_OP', 'MEDREIMB_CAR', 'BENRES_CAR', 'PPPYMT_CAR', 'year', 'SEX',
       'RACE', 'STATE', 'claim_year', 'num_claim_lines', 'avg_claim_duration',
       'max_claim_duration', 'total_claim_duration',
       'avg_carrier_rejected_amt', 'max_carrier_rejected_amt',
       'total_carrier_rejected_amt', 'avg_carrier_claim_rejected_rate (%)',
       'max_carrier_claim_rejected_rate (%)', 'avg_reimb_allowed_diff',
       'min_reimb_allowed_diff', 'max_reimb_allowed_diff',
       'total_reimb_allowed_diff', 'max_chronic_code_counts',
       'has_Additional endocrine/metabolic burden', 'has_COPD',
       'has_Administrative_screening_aftercare', 'has_Cancer',
       'has_Injury/Frailty Burden', 'has_Additional cardiovascular burden',
       'has_Additional mental health burden',
       'has_Additional Musculoskeletal Burden',
       'has_Infectious disease burden', 'has_Stroke/TIA',
       'has_Additional neurologic burden', 'has_Diabetes',
       'has_Additional renal burden', 'has_Genitourinary (non-renal) burden',
       'has_Sensory Burden', 'has_Additional Hematologic burden',
       'has_Rheumatoid Arthritis/Osteoarthritis', 'has_Depression',
       'has_Heart Failure', 'has_CKD', 'has_Additional GI/Hepatic burden'],
      dtype='object')

In [5]:
inpatient.columns

Index(['DESYNPUF_ID', 'claim_year', 'num_ip_claims', 'avg_claim_duration',
       'max_claim_duration', 'total_claim_duration', 'avg_ip_pmt',
       'max_ip_pmt', 'total_ip_pmt', 'max_chronic_code_counts',
       'has_Infectious disease burden', 'has_Injury/Frailty Burden', 'has_CKD',
       'has_Additional endocrine/metabolic burden',
       'has_Additional renal burden', 'has_Additional cardiovascular burden',
       'has_Additional neurologic burden', 'has_Additional GI/Hepatic burden',
       'has_Additional Hematologic burden', 'has_Sensory Burden', 'has_Cancer',
       'has_Additional mental health burden', 'has_Stroke/TIA',
       'has_Depression', 'has_Diabetes',
       'has_Administrative_screening_aftercare',
       'has_Additional Musculoskeletal Burden', 'has_COPD',
       'has_Rheumatoid Arthritis/Osteoarthritis', 'has_Heart Failure',
       'has_Genitourinary (non-renal) burden'],
      dtype='object')